### ISSUE TITLE
Add information about attachments in REST API

### ISSUE THREAD

**Issue by tommywo** [jhillyerd/inbucket#32] opened 2016-03-22 06:51 UTC
I would see it llike that:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 810
Date: Thu, 17 Oct 2013 21:51:59 GMT

{
    "mailbox": "swaks",
    "id": "20131016T164638-0001",
    "from": "jamehi03@server.com",
    "subject": "Swaks HTML",
    "date": "2013-10-16T16:46:38.646370568-07:00",
    "size": 705,
    "body": {
        "text": "This is a test mailing.\r\n\r\nThis should be clickable: http://google.com/\r\n",
        "html": "<html>\n<body>\n<p>This is a test mailing <b>in HTML</b></p>\n\n<p>This should be clickable: [...]"
    },
    "header": {
        "Content-Type": [
            "multipart/alternative; boundary=\"----=_MIME_BOUNDARY_000_62717\""
        ],
        "Date": [
            "Wed, 16 Oct 2013 16:46:38 -0700"
        ],
        "From": [
            "jamehi03@server.com"
        ],
        "Mime-Version": [
            "1.0"
        ],
        "Subject": [
            "Swaks HTML"
        ],
        "To": [
            "swaks@inbucket.local"
        ]
    },
   "attachments": [
    {
      "filename": "file.png",
      "content-type": "image/png",
      "downloadLink": "linkHere",
      "viewLink": "linkHere",
      "md5: "hashHere"
     }
    ]
}
```

**Comment by jhillyerd** [comment] 2016-03-22 15:12
That seems doable.  Right now our MIME parser breaks multiparts into three categories: inlines, attachments and others.  https://github.com/jhillyerd/go.enmime/blob/master/mail.go#L12

We will need to figure out which of those should be returned, and whether it's in a single list with an attribute to signify type, or in a few separate lists.

**Comment by MatWisz** [comment] 2016-12-30 07:09
Issue resolved with #46. To close

**Closed** 2016-12-31 01:09 UTC
Labels: enhancement

**Comment by MatWisz** [comment] 2017-01-26 07:58
Can you change milestone of this issue to v1.1.1 and release this version. I need this feature but version v1.2.0 is now completed only in 30%

**Comment by jhillyerd** [comment] 2017-01-26 17:47
Doing a release takes quite a bit of time for me, and the 30% isn't accurate, I think it's closer to 90%.   #12 and #31 are the only code changes left before beta.

GitHub doesn't count the percentage until the issue is closed, but I prefer to leave them open until they've made it into a beta release so I don't get duplicate bug reports filed.  For now I am using the `completed` tag to indicate finished work. 

The develop branch is working well for me right now, so you could build that from source - or if you are using the Docker hub image, use the latest tag: jhillyerd/inbucket:latest
